version: "3"
services:
  base:
    image: librealsense:v2.50.0
    build: 
      context: .
      dockerfile: Dockerfile
      target: realsenseros
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: roslaunch realsense2_camera rs_camera.launch
    # Networking
    network_mode: "host"
    ipc: host
  
  ## Nvidia Jetson Deep Learning
  # camera_detection:
  #   image: dustynv/ros:humble-ros-core-l4t-r32.7.1 # Check this first for Jetpack version
  #   command: ros2 launch ros_deep_learning video_source.ros2.launch input:=csi://0
  #   # Networking
  #   network_mode: "host"
  #   ipc: host

  ## Foxglove
  # foxglove-websocket:
  #   image:  base_image:base
  #   command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
  #   # Networking
  #   network_mode: "host"
  #   ipc: host

  # foxglove-server:
  #   image: ghcr.io/foxglove/studio:latest
  #   ports:
  #     - "8080:8080"
  #   network_mode: "host"
  #   ipc: host